// Generated from Oracle's Full Parameter Reference by scripts/syncOracleParameterCatalog.mjs.
// Do not edit this file by hand; update the generator or supplemental catalog instead.
import type { OracleParameterCatalogEntry } from '../models';

export const FULL_REFERENCE_PARAMETER_ENTRIES = [
  {
    name: 'data.page-uri',
    displayName: 'Page URI',
    description: 'data.page-uri indicates the URI of the page or the mobile app screen.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/content_group.htm#data.page-uri',
  },
  {
    name: 'datetime_utc',
    displayName: 'Date',
    description:
      "datetime_utc indicates the date and time in UTC format based on the value of wt.ets (if sent). If wt.ets is not sent, Oracle Infinity's data collection server generates the value of datetime_utc when it receives the event data.",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/datetime_utc.htm',
  },
  {
    name: 'dcsipa',
    displayName: 'IP address maskng',
    description: 'dcsipa allows you to mask IP addresses by specifying the optional value of 1.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/ip_address_masking.htm',
  },
  {
    name: 'ext.browser.mfr',
    displayName: 'Browser manufacturer',
    description: 'ext.browser.mfr identifies the browser manufacturer.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/browser_os.htm#ext.browser.mfr',
  },
  {
    name: 'ext.browser.name',
    displayName: 'Browser name',
    description:
      'ext.browser.name identifies the name of the browser or browser group, such as Chrome.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/browser_os.htm#ext.browser.name',
  },
  {
    name: 'ext.browser.renderer',
    displayName: 'Browser rendering engine',
    description: "ext.browser.renderer identifies the browser's rendering engine, such as GECKO.",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/browser_os.htm#ext.browser.renderer',
  },
  {
    name: 'ext.browser.type',
    displayName: 'Browser type',
    description:
      'ext.browser.type identifies the type of browser, such as email client or browser.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/browser_os.htm#ext.browser.type',
  },
  {
    name: 'ext.browser.version',
    displayName: 'Browser version',
    description: 'ext.browser.version identifies the browser version, such as 11.0.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/browser_os.htm#ext.browser.version',
  },
  {
    name: 'ext.browser.vmajor',
    displayName: 'Major browser version',
    description: 'ext.browser.vmajor identifies the major version of the browser.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/browser_os.htm#ext.browser.vmajor',
  },
  {
    name: 'ext.browser.vminor',
    displayName: 'Minor browser version',
    description:
      'ext.browser.vminor identifies the minor version of the browser, which is typically the second decimal.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/browser_os.htm#ext.browser.vminor',
  },
  {
    name: 'ext.device.androidos',
    displayName: 'Android',
    description:
      'ext.device.androidos indicates whether the device is distributed with Android OS preinstalled ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.androidos',
  },
  {
    name: 'ext.device.bada',
    displayName: 'Bada OS',
    description:
      'ext.device.bada indicates whether the device is distributed with Bada OS pre-installed ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.bada',
  },
  {
    name: 'ext.device.brand',
    displayName: 'OEM name',
    description:
      'ext.device.brand indicates the name of the original equipment manufacturer (OEM) of the device, browser, or other component (such as Mozilla).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.brand',
  },
  {
    name: 'ext.device.devp',
    displayName: 'Developer platform',
    description:
      'ext.device.devp indicates the commercial name of the developer platform that the device was built around (if any).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.devp',
  },
  {
    name: 'ext.device.devpv',
    displayName: 'Developer platform version',
    description:
      'ext.device.devpv indicates the version of the developer platform that the device was built around (if any).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.devpv',
  },
  {
    name: 'ext.device.dsktpbr',
    displayName: 'Desktop browser',
    description:
      'ext.device.dsktpbr indicates whether the device is using a desktop browser ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.dsktpbr',
  },
  {
    name: 'ext.device.ereader',
    displayName: 'Reading device',
    description:
      'ext.device.ereader indicates whether the device is a reading device ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.ereader',
  },
  {
    name: 'ext.device.flash',
    displayName: 'Flash capability',
    description:
      'ext.device.flash indicates whether the device supports Flash ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.flash',
  },
  {
    name: 'ext.device.gamec',
    displayName: 'Game console',
    description:
      'ext.device.gamec indicates whether the device is a game console ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.gamec',
  },
  {
    name: 'ext.device.html5c',
    displayName: 'HTML5 support',
    description:
      "ext.device.html5c indicates whether the device's browser supports HTML5 ( true ) or not ( false ).",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.html5c',
  },
  {
    name: 'ext.device.https',
    displayName: 'HTTPS capability',
    description:
      "ext.device.https indicates whether the device's browser supports secure sockets layer ( true ) or not ( false ).",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.https',
  },
  {
    name: 'ext.device.id',
    displayName: 'Device ID',
    description: 'ext.device.id provides the unique ID of the device if properly detected.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.id',
  },
  {
    name: 'ext.device.ios',
    displayName: 'iOS',
    description:
      'ext.device.iOS indicates whether the device is distributed with iOS preinstalled ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.iOS',
  },
  {
    name: 'ext.device.medp',
    displayName: 'Media player',
    description:
      'ext.device.medp indicates whether the device is a media player ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.medp',
  },
  {
    name: 'ext.device.mktn',
    displayName: 'Marketing name',
    description: 'ext.device.mktn indicates the marketing name for a device.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.mktn',
  },
  {
    name: 'ext.device.mobile',
    displayName: 'Mobile device',
    description:
      'ext.device.mobile indicates whether the device is meant for use on the move ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.mobile',
  },
  {
    name: 'ext.device.model',
    displayName: 'Model name',
    description:
      'ext.device.model indicates the model name of the device, browser, or other component (such as Firefox).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.model',
  },
  {
    name: 'ext.device.osver',
    displayName: 'OS version',
    description:
      'ext.device.osver indicates the version of the preinstalled operating system, such as 6_1_2 or null if not defined.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.osver',
  },
  {
    name: 'ext.device.rim',
    displayName: 'RIM OS',
    description:
      'ext.device.rim indicates whether the device is distributed with RIM OS preinstalled ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.rim',
  },
  {
    name: 'ext.device.scres',
    displayName: 'Screen resolution',
    description: 'ext.device.scres indicates the width and height of the device screen.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.scres',
  },
  {
    name: 'ext.device.smphone',
    displayName: 'Mobile phone',
    description:
      'ext.device.smphone indicates whether the device is a mobile phone ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.smphone',
  },
  {
    name: 'ext.device.stb',
    displayName: 'Set-top box',
    description:
      'ext.device.stb indicates whether the device is a set-top box ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.stb',
  },
  {
    name: 'ext.device.symb',
    displayName: 'Symbian OS',
    description:
      'ext.device.symb indicates whether the device is distributed with Symbian OS preinstalled ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.symb',
  },
  {
    name: 'ext.device.tablet',
    displayName: 'Tablet',
    description:
      'ext.device.tablet indicates whether the device is a tablet ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.tablet',
  },
  {
    name: 'ext.device.touch',
    displayName: 'Touchscreen',
    description:
      'ext.device.touch indicates whether the device has a touchscreen ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.touch',
  },
  {
    name: 'ext.device.tv',
    displayName: 'Television',
    description:
      'ext.device.tv indicates whether the device is a television ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.tv',
  },
  {
    name: 'ext.device.webos',
    displayName: 'WebOS',
    description:
      'ext.device.webos indicates whether the device is distributed with WebOS preinstalled ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.webos',
  },
  {
    name: 'ext.device.winm',
    displayName: 'Windows Mobile',
    description:
      'ext.device.winm indicates whether the device is distributed with Windows Mobile preinstalled ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.winm',
  },
  {
    name: 'ext.device.winp',
    displayName: 'Windows Phone',
    description:
      'ext.device.winp indicates whether the device is distributed with Windows Phone preinstalled ( true ) or not ( false ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.winp',
  },
  {
    name: 'ext.device.yrel',
    displayName: 'Device year',
    description: 'ext.device.yrel indicates the year the device was released or announced.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/device.htm#ext.device.yrel',
  },
  {
    name: 'ext.geo.area',
    displayName: 'Area Code',
    description: 'ext.geo.area indicates the US telephone area code.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.area',
  },
  {
    name: 'ext.geo.cbsac',
    displayName: 'CBSA code',
    description:
      'ext.geo.cbsac indicates the core-based statistical area (CBSA) internal lookup code (US only).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.cbsac',
  },
  {
    name: 'ext.geo.cbsan',
    displayName: 'CBSA title',
    description:
      'ext.geo.cbsan indicates the CBSA title for the location, such as San Francisco-Oakland-Fremont, CA.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.cbsan',
  },
  {
    name: 'ext.geo.cbsat',
    displayName: 'CBSA type',
    description:
      'ext.geo.cbsat indicates the type of CBSA, which can be a metropolitan ( metro ) or a micro area.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.cbsat',
  },
  {
    name: 'ext.geo.cc2',
    displayName: 'Country two-letter code',
    description: 'ext.geo.cc2 indicates the ISO 3166-1 alpha-2 country code, such as US.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.cc2',
  },
  {
    name: 'ext.geo.cc3',
    displayName: 'Country three-letter code',
    description: 'ext.geo.cc3 indicates the ISO 3166-1 alpha-3 country code, such as GBR.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.cc3',
  },
  {
    name: 'ext.geo.cic',
    displayName: 'City code',
    description:
      'ext.geo.cic identifies the numeric code for the city, such as 4782 for London, UK, which is useful for filtering.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.cic',
  },
  {
    name: 'ext.geo.city',
    displayName: 'City',
    description: 'ext.geo.city identifies the full name of the city, such as London.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.city',
  },
  {
    name: 'ext.geo.cnc',
    displayName: 'Continent code',
    description: 'ext.geo.cnc indicates the numeric code for the continent.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.cnc',
  },
  {
    name: 'ext.geo.co',
    displayName: 'Company',
    description:
      'ext.geo.co indicates the name of the company. If no specific company name exists, the ISP name appears.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.co',
  },
  {
    name: 'ext.geo.continent',
    displayName: 'Continent name',
    description: 'ext.geo.continent indicates the continent name.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.continent',
  },
  {
    name: 'ext.geo.country',
    displayName: 'Country',
    description: 'ext.geo.country indicates the full name of the country.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.country',
  },
  {
    name: 'ext.geo.csac',
    displayName: 'CSA code',
    description:
      'ext.geo.csac identifies the combined statistical area ( CSA ) code, which is similar to the core-based statistical area (CBSA).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.csac',
  },
  {
    name: 'ext.geo.csan',
    displayName: 'CSA title',
    description:
      'ext.geo.csan indicates the combined statistical area ( CSA ) title, such as San Jose-San Francisco-Oakland.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.csan',
  },
  {
    name: 'ext.geo.dst',
    displayName: 'Daylight saving time',
    description:
      'ext.geo.dst indicates whether the region is observing daylight saving time ( y ) or not ( n ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.dst',
  },
  {
    name: 'ext.geo.hb',
    displayName: 'Home or business',
    description:
      'ext.geo.hb indicates whether the hit is from a home or business based on registration of the IP address with an ISP.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.hb',
  },
  {
    name: 'ext.geo.isp',
    displayName: 'ISP name',
    description: 'ext.geo.isp indicates the name of the ISP.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.isp',
  },
  {
    name: 'ext.geo.ispd',
    displayName: 'ISP domain',
    description:
      'ext.geo.ispd indicates the internet service provider (ISP) domain name, such as comcast.net.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.ispd',
  },
  {
    name: 'ext.geo.latitude',
    displayName: 'Latitude',
    description:
      'ext.geo.latitude indicates the approximate latitude coordinate, such as -051.506.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.latitude',
  },
  {
    name: 'ext.geo.longitude',
    displayName: 'Longitude',
    description:
      'ext.geo.longitude indicates the approximate longitude coordinate, such as -000.127.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.longitude',
  },
  {
    name: 'ext.geo.metro',
    displayName: 'Metropolitan area name',
    description: 'ext.geo.metro indicates the name of the metropolitan area.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.metro',
  },
  {
    name: 'ext.geo.mtc',
    displayName: 'Metro code',
    description: 'ext.geo.mtc indicates the 2-6 digit metro codes, such as 505 for Detroit.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.mtc',
  },
  {
    name: 'ext.geo.mts',
    displayName: 'State',
    description: "ext.geo.mts indicates the state of the visitor's designated market area (DMA).",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.mts',
  },
  {
    name: 'ext.geo.nt',
    displayName: 'Network type',
    description:
      'ext.geo.nt indicates the type of network connection, such as broadband, xdsl, cable, or mobile.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.nt',
  },
  {
    name: 'ext.geo.plang',
    displayName: 'Region language',
    description: 'ext.geo.plang indicates the primary language in the region.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.plang',
  },
  {
    name: 'ext.geo.rc',
    displayName: 'Region code',
    description: 'ext.geo.rc identifies the two-letter region code, such as NY.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.rc',
  },
  {
    name: 'ext.geo.region',
    displayName: 'Region',
    description: 'ext.geo.region indicates the name of the region.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.region',
  },
  {
    name: 'ext.geo.tz',
    displayName: 'Time zone offset',
    description: 'ext.geo.tz identifies the UTC offset.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.tz',
  },
  {
    name: 'ext.geo.zip',
    displayName: 'Zip Code',
    description: 'ext.geo.zip indicates the postal code.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/geolocation.htm#ext.geo.zip',
  },
  {
    name: 'ext.os.mfr',
    displayName: 'OS manufacturer',
    description: 'ext.os.mfr identifies the operating system manufacturer, such as Microsoft.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/browser_os.htm#ext.os.mfr',
  },
  {
    name: 'ext.os.name',
    displayName: 'OS name',
    description: 'ext.os.name identifies the name of the operating system, such as Android.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/browser_os.htm#ext.os.name',
  },
  {
    name: 'ext.search.engine',
    displayName: 'Search engine',
    description: 'ext.search.engine indicates the search engine used.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/traffic_source_and_search.htm#ext.search.engine',
  },
  {
    name: 'ext.search.paid',
    displayName: 'Paid search engine',
    description: 'ext.search.paid populates the WT.srch=1 parameter.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/traffic_source_and_search.htm#ext.search.paid',
  },
  {
    name: 'ext.search.phrase',
    displayName: 'Search phrase',
    description: 'ext.search.phrase indicates the search phrase used.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/traffic_source_and_search.htm#ext.search.phrase',
  },
  {
    name: 'ext.source.name',
    displayName: 'Referer name',
    description: 'ext.source.name indicates the actual name of the referer.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/traffic_source_and_search.htm#ext.source.name',
  },
  {
    name: 'ext.source.type',
    displayName: 'Traffic source type',
    description: 'ext.source.type indicates the type of traffic source.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/traffic_source_and_search.htm#ext.source.type',
  },
  {
    name: 'session.closed',
    displayName: 'Active or closed',
    description:
      '( Streams only) session.closed indicates whether the session is active ( false ) or closed ( true ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_session.htm#session.closed',
  },
  {
    name: 'session.closed_reason',
    displayName: 'Reason for closing',
    description: '( Streams only) session.closed_reason indicates a reason for a closed session.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_session.htm#session.closed_reason',
  },
  {
    name: 'session.duration.limit',
    displayName: 'Duration limit',
    description:
      '( Streams only) session.duration.limit indicates the maximum time, in milliseconds, for an active session until the session is closed.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_session.htm#session.duration.limit',
  },
  {
    name: 'session.event_count',
    displayName: 'Events received',
    description:
      '( Streams only) session.event_count identifies the number of events received in the session.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_session.htm#session.event_count',
  },
  {
    name: 'session.first_datetime_utc',
    displayName: 'Start time',
    description:
      '( Streams only) session.first_datetime_utc indicates the start time of the session.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_session.htm#session.first_datetime_utc',
  },
  {
    name: 'session.page_view_count',
    displayName: 'Active or closed',
    description:
      '( Streams only) session.page_view_count identifies the number of pages viewed in the session.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_session.htm#session.page_view_count',
  },
  {
    name: 'session.recent_datetime_utc',
    displayName: 'Time of most recent event',
    description:
      '( Streams only) session.recent_datetime_utc indicates the time of the most recent or last event in the session.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_session.htm#session.recent_datetime_utc',
  },
  {
    name: 'session.returning_visitor',
    displayName: 'New or returning visitor',
    description:
      '( Streams only) session.returning_visitor indicates whether this is a new visitor ( false ) or a returning visitor ( true ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_session.htm#session.returning_visitor',
  },
  {
    name: 'session.session_id',
    displayName: 'Session ID',
    description: '( Streams only) session.session_id indicates the unique ID of the session.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_session.htm#session.session_id',
  },
  {
    name: 'session.time_inactive',
    displayName: 'Time inactive',
    description:
      '( Streams only) session.time_inactive indicates the time, in milliseconds, since the last event from the visitor.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_session.htm#session.time_inactive',
  },
  {
    name: 'session.time_on_site',
    displayName: 'Duration',
    description:
      '( Streams only) session.time_on_site indicates the duration, in seconds, of the session.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_session.htm#session.time_on_site',
  },
  {
    name: 'session.visitor_id',
    displayName: 'Visitor ID',
    description: 'session.visitor_id provides the unique visitor ID.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_session.htm#session.visitor_id',
  },
  {
    name: 'wt.a_ac',
    displayName: 'App ad click',
    description: 'wt.a_ac indicates that an ad was clicked within a mobile app.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.a_ac',
    reportingNameNote:
      'Collection name wt.a_ac; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.a_ai',
    displayName: 'App ad impression',
    description: 'wt.a_ai indicates that one or more ads was viewed in a mobile app.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.a_ai',
    reportingNameNote:
      'Collection name wt.a_ai; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.a_an',
    displayName: 'App ad name',
    description: 'wt.a_an specifies one more names of ads presented in a mobile app.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.a_an',
    reportingNameNote:
      'Collection name wt.a_an; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.a_cat',
    displayName: 'App category',
    description:
      'wt.a_cat specifies a category of mobile app, such as Games, Health & Wellness, or Productivity.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.a_cat',
    reportingNameNote:
      'Collection name wt.a_cat; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.a_dc',
    displayName: 'Mobile Carrier',
    description: 'wt.a_dc specifies the mobile carrier.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.a_dc',
    reportingNameNote:
      'Collection name wt.a_dc; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.a_nm',
    displayName: 'Mobile App Name',
    description: 'wt.a_nm specifies the name of the mobile app.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.a_nm',
    reportingNameNote:
      'Collection name wt.a_nm; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.a_pub',
    displayName: 'App publisher',
    description: 'WT.a_pub specifies the developer, publisher, or vendor for a mobile app.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.a_pub',
    reportingNameNote:
      'Collection name wt.a_pub; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.ac',
    displayName: 'Ad click',
    description: 'wt.ac specifies the name of an ad clicked to reach a particular web page.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/ad.htm#wt.ac',
    reportingNameNote:
      'Collection name wt.ac; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.ad',
    displayName: 'Ad view',
    description:
      'wt.ad specifies the names of one or more semicolon-delimited ads viewed on a web page.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/ad.htm#wt.ad',
    reportingNameNote:
      'Collection name wt.ad; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.av',
    displayName: 'Mobile App Version',
    description: 'wt.av specifies the version of the mobile app.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.av',
    reportingNameNote:
      'Collection name wt.av; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.bh',
    displayName: 'Local time',
    description:
      'wt.bh indicates the web client’s browsing hour (local time of day on a 24-hour clock).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/web-client.htm#wt.bh',
    reportingNameNote:
      'Collection name wt.bh; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.bs',
    displayName: 'Window size',
    description: 'wt.bs indicates the width and height of the web client window in pixels.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/web-client.htm#wt.ul',
    reportingNameNote:
      'Collection name wt.bs; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.cd',
    displayName: 'Screen color depth',
    description: 'wt.cd indicates the web client’s screen color depth.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/web-client.htm#wt.cd',
    reportingNameNote:
      'Collection name wt.cd; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.ce',
    displayName: 'Cookies enabled',
    description:
      'wt.ce indicates whether the visitor has first-party cookies enabled ( 1 ) or disabled ( 0 ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/cookie_detection.htm#wt.ce',
    reportingNameNote:
      'Collection name wt.ce; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.cg_n',
    displayName: 'Content group name',
    description: 'wt.cg_n identifies one or more semicolon-delimited content group names.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/content_group.htm#wt.cg_n',
    reportingNameNote:
      'Collection name wt.cg_n; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.cg_s',
    displayName: 'Content subgroup name',
    description: 'wt.cg_s identifies one or more semicolon-delimited content subgroup names.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/content_group.htm#wt.cg_s',
    reportingNameNote:
      'Collection name wt.cg_s; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.cgm_ev',
    displayName: 'CGM event',
    description:
      'wt.cgm_ev identifies the consumer-generated media (CGM) event that occurred, such as a post ( p ) or comment ( c ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/content.htm#wt.cgm_ev',
    reportingNameNote:
      'Collection name wt.cgm_ev; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.cgm_t',
    displayName: 'CGM type',
    description: 'wt.cgm_t identifies the type of consumer-generated media.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/content.htm#wt.cgm_t',
    reportingNameNote:
      'Collection name wt.cgm_t; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_accountid',
    displayName: 'Brightcove account ID',
    description: 'wt.clip_accountid provides the unique ID of the Brightcove account.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_accountid',
    reportingNameNote:
      'Collection name wt.clip_accountid; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_ct',
    displayName: 'Video content type',
    description: "wt.clip_ct indicates the video's content type, such as MOV.",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_ct',
    reportingNameNote:
      'Collection name wt.clip_ct; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_duration',
    displayName: 'Duration in seconds',
    description: 'wt.clip_duration indicates the video duration in seconds.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_duration',
    reportingNameNote:
      'Collection name wt.clip_duration; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_duration_min',
    displayName: 'Duration in minutes',
    description: 'wt.clip_duration_min indicates the video duration in minutes.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_duration_min',
    reportingNameNote:
      'Collection name wt.clip_duration_min; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_duration_n',
    displayName: 'Duration based on range',
    description: 'wt.clip_duration_n indicates the range of the video duration in seconds.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_duration_n',
    reportingNameNote:
      'Collection name wt.clip_duration_n; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_ev',
    displayName: 'Media event identifier',
    description:
      'wt.clip_ev identifies the type of media-related event that has occurred, such as v for a view event.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_ev',
    reportingNameNote:
      'Collection name wt.clip_ev; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_id',
    displayName: 'Video identifier',
    description: 'wt.clip_id indicates the unique ID of the video asset.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_id',
    reportingNameNote:
      'Collection name wt.clip_id; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_mins',
    displayName: 'Playhead in minutes',
    description: "wt.clip_mins indicates the video's playhead position in minutes.",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_mins',
    reportingNameNote:
      'Collection name wt.clip_mins; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_mode',
    displayName: 'Mode type',
    description:
      'wt.clip_mode identifies the mode type of video, such as fixed, streaming, FullScreenOn, or FullScreenOff.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_mode',
    reportingNameNote:
      'Collection name wt.clip_mode; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_n',
    displayName: 'Video name',
    description: 'wt.clip_n identifies the name of the video that was accessed.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_n',
    reportingNameNote:
      'Collection name wt.clip_n; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_perc',
    displayName: 'Percentage played',
    description: 'wt.clip_perc identifies the percentage of the video that the viewer has played.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_perc',
    reportingNameNote:
      'Collection name wt.clip_perc; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_player',
    displayName: 'Player name',
    description: 'wt.clip_player identifies the name of the video player.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_player',
    reportingNameNote:
      'Collection name wt.clip_player; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_player_res',
    displayName: 'Player resolution',
    description:
      "wt.clip_player_res indicates the video player's resolution in pixel height x width.",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_player_res',
    reportingNameNote:
      'Collection name wt.clip_player_res; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_provider',
    displayName: 'Video provider',
    description: 'WT.clip_provider indicates the host on which the video is located',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_provider',
    reportingNameNote:
      'Collection name wt.clip_provider; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_res',
    displayName: 'Video resolution',
    description:
      'wt.clip_res indicates the resolution of the video expressed as height x width in pixels.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_res',
    reportingNameNote:
      'Collection name wt.clip_res; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_secs',
    displayName: 'Playhead in seconds',
    description: "wt.clip_secs indicates the video's playhead position in seconds.",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_secs',
    reportingNameNote:
      'Collection name wt.clip_secs; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_src',
    displayName: 'Video URL',
    description: 'wt.clip_src provides the URL of the video.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_src',
    reportingNameNote:
      'Collection name wt.clip_src; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_t',
    displayName: 'Media type',
    description:
      'wt.clip_t identifies the type of media, such as Flash or HTML5, depending on what type of player is being used.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_t',
    reportingNameNote:
      'Collection name wt.clip_t; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_tags',
    displayName: 'Video tags',
    description: 'wt.clip_tags provides a list of one or more semicolon-delimited video tags.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_tags',
    reportingNameNote:
      'Collection name wt.clip_tags; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_tv',
    displayName: 'Video tag plugin version',
    description: 'wt.clip_tv provides the version of the video tag plugin.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_tv',
    reportingNameNote:
      'Collection name wt.clip_tv; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_video_id',
    displayName: 'Brightcove video ID',
    description: 'wt.clip_video_id provides the unique ID of the Brightcove video.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_video_id',
    reportingNameNote:
      'Collection name wt.clip_video_id; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.clip_vol',
    displayName: 'Volume level',
    description: 'wt.clip_vol provides the volume of the video on a scale from 1 through 100.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.clip_vol',
    reportingNameNote:
      'Collection name wt.clip_vol; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.co_f',
    displayName: 'First-party cookie',
    description:
      'wt.co_f is a random value used as a visitor ID and stored in a first-party cookie.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/cookie_detection.htm#wt.co_f',
    reportingNameNote:
      'Collection name wt.co_f; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.com_v',
    displayName: 'Website test variant',
    description:
      'wt.com_v identifies the website test variant used to compare activity, such as the scenario step conversion rate of two or more test variants.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/content.htm#wt.com_v',
    reportingNameNote:
      'Collection name wt.com_v; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.conv',
    displayName: 'Conversion name',
    description:
      'wt.conv specifies a name used to identify a customer conversion event, which can be any conversion event that you define on your site or app.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/conversion.htm',
    reportingNameNote:
      'Collection name wt.conv; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.ct',
    displayName: 'Connection type',
    description: 'wt.ct specifies the connection type used to send data.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.ct',
    reportingNameNote:
      'Collection name wt.ct; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.dcs_id',
    displayName: 'DCSID',
    description:
      '(Deprecated) wt.dcs_id is a unique ID associated with a data source for data collected from a website or app.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/dcsid.htm',
    reportingNameNote:
      'Collection name wt.dcs_id; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.dcsvid',
    displayName: 'External visitor ID',
    description:
      'wt.dcsvid identifies an optional unique custom visitor ID you can assign to your visitors in other systems. This is separate and distinct from automatically generated visitor ID parameters sent by the Oracle Infinity Tag. If you do not send a custom value, this parameter will not be present on the hit.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/stored_visitor.htm',
    reportingNameNote:
      'Collection name wt.dcsvid; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.dep',
    displayName: 'Encoding conversion',
    description:
      'wt.dep contains a semicolon-delimited list of custom DCSext query parameters on a web page. The encoding conversion plugin uses this information to identify the parameters that are known to be encoded in UTF-8.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/conversion_plugin.htm',
    reportingNameNote:
      'Collection name wt.dep; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.dl',
    displayName: 'Event tracking',
    description:
      'wt.dl specifies a numeric identifier for the kind of event tracked, which are used for event-level filtering and reporting.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/event_tracking.htm',
    reportingNameNote:
      'Collection name wt.dl; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.dm',
    displayName: 'Device model',
    description:
      'wt.dm specifies the model of the mobile device that an application is running on, such as wt.dm=iPhone%207.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.dm',
    reportingNameNote:
      'Collection name wt.dm; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.es',
    displayName: 'Page URL',
    description: 'wt.es identifies the page a user was on when an event occurred.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/click_tracking.htm',
    reportingNameNote:
      'Collection name wt.es; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.ets',
    displayName: 'Event time stamp',
    description: 'wt.ets indicates the Unix time stamp for the event measured in milliseconds.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.ets',
    reportingNameNote:
      'Collection name wt.ets; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.ev',
    displayName: 'Event type',
    description:
      'wt.ev specifies the type of event activity on a mobile device, such as clicks, swipes, and content views.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.ev',
    reportingNameNote:
      'Collection name wt.ev; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.g_co',
    displayName: 'Country',
    description: 'wt.g_co specifies the country of origin for mobile traffic using a country code.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.g_co',
    reportingNameNote:
      'Collection name wt.g_co; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.gc',
    displayName: 'Geolocation coordinates',
    description: 'wt.gc indicates the latitude and longitude of a mobile device.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.gc',
    reportingNameNote:
      'Collection name wt.gc; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.hdr',
    displayName: 'HTTP header',
    description:
      'wt.hdr identifies the value of the custom HTTP headers, such as those inserted by third-party load balancers, application servers, or web server plugins.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/http_headers.htm',
    reportingNameNote:
      'Collection name wt.hdr; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.hp',
    displayName: 'Home page',
    description:
      "wt.hp indicates whether the viewed page was set as the web client's home page ( 1 ) or not ( 0 ).",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/web-client.htm#wt.hp',
    reportingNameNote:
      'Collection name wt.hp; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.jo',
    displayName: 'Java enabled',
    description: 'wt.jo indicates whether the web client has enabled Java ( yes ) or not ( no ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/web-client.htm#wt.jo',
    reportingNameNote:
      'Collection name wt.jo; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.js',
    displayName: 'JavaScript enabled',
    description:
      'wt.js indicates whether the web client supports or has enabled JavaScript ( yes ) or not ( no ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/web-client.htm#wt.js',
    reportingNameNote:
      'Collection name wt.js; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.jv',
    displayName: 'JavaScript version',
    description: 'wt.jv indicates the version of JavaScript supported by the web client.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/web-client.htm#wt.jv',
    reportingNameNote:
      'Collection name wt.jv; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.le',
    displayName: 'Character set',
    description:
      'wt.le indicates the character set used by the web client to render the current document.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/web-client.htm#wt.le',
    reportingNameNote:
      'Collection name wt.le; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.mc_ev',
    displayName: 'Campaign event',
    description:
      'wt.mc_ev identifies the ad event type, such as click for an ad clickthrough event.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/campaign.htm#wt.mc_ev',
    reportingNameNote:
      'Collection name wt.mc_ev; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.mc_id',
    displayName: 'Campaign ID',
    description: 'wt.mc_id associates pages with a specific campaign.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/campaign.htm#wt.mc_id',
    reportingNameNote:
      'Collection name wt.mc_id; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.nv',
    displayName: 'Div or table',
    description:
      'wt.nv contains the ID or class of the parent <div/> or <table/> of the element that was clicked so that you can track the corresponding page areas.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/div_table.htm',
    reportingNameNote:
      'Collection name wt.nv; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.oss',
    displayName: 'Search phrase',
    description: 'wt.oss identifies a word or a phrase that visitors submit for an on-site search.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/on-site_search.htm#wt.oss',
    reportingNameNote:
      'Collection name wt.oss; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.oss_r',
    displayName: 'Search success',
    description:
      "wt.oss_r indicates whether an on-site search is successful by capturing the number of search results. If its value is 0, the user's search failed.",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/on-site_search.htm#wt.oss_r',
    reportingNameNote:
      'Collection name wt.oss_r; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.p_did',
    displayName: 'Device persona',
    description: 'wt.p_did provides a hash value that represents the device used by the visitor.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/persona_service.htm#wt.p_did',
    reportingNameNote:
      'Collection name wt.p_did; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.p_pid',
    displayName: 'Persona ID',
    description:
      'wt.p_pid provides a hashed persona identifier generated by the persona service. wt.p_pid is typically identical to wt.p_vid',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/persona_service.htm#wt.p_pid',
    reportingNameNote:
      'Collection name wt.p_pid; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.p_sid',
    displayName: 'Session persona',
    description: 'wt.p_sid provides a unique ID for the session for use by the persona service.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/persona_service.htm#wt.p_sid',
    reportingNameNote:
      'Collection name wt.p_sid; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.p_vid',
    displayName: 'New persona',
    description:
      'wt.p_vid is generated if the wt.p_did does not match an existing persona. If the persona is matched, wt.p_vid is identical to wt.p_pid.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/persona_service.htm#wt.p_vid',
    reportingNameNote:
      'Collection name wt.p_vid; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.pi',
    displayName: 'Page of interest',
    description: 'wt.pi identifies a page of interest on your site or name of a mobile app.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/page-of-interest.htm',
    reportingNameNote:
      'Collection name wt.pi; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.player_id',
    displayName: 'Brightcove playlist ID',
    description: 'wt.player_id provides the unique ID of the Brightcove playlist.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/video_content.htm#wt.player_id',
    reportingNameNote:
      'Collection name wt.player_id; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.pn_fa',
    displayName: 'Product family',
    description: 'wt.pn_fa identifies the product family.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/products.htm#wt.pn_fa',
    reportingNameNote:
      'Collection name wt.pn_fa; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.pn_gr',
    displayName: 'Product group',
    description: 'wt.pn_gr identifies the product group.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/products.htm#wt.pn_gr',
    reportingNameNote:
      'Collection name wt.pn_gr; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.pn_id',
    displayName: 'Product ID',
    description: 'wt.pn_id identifies a unique product ID.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/products.htm#wt.pn_id',
    reportingNameNote:
      'Collection name wt.pn_id; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.pn_ma',
    displayName: 'Product manufacturer',
    description: 'wt.pn_ma identifies the manufacturer of the product.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/products.htm#wt.pn_ma',
    reportingNameNote:
      'Collection name wt.pn_ma; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.pn_sc',
    displayName: 'Product subgroup',
    description: 'wt.pn_sc identifies the product subgroup.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/products.htm#wt.pn_sc',
    reportingNameNote:
      'Collection name wt.pn_sc; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.pn_sku',
    displayName: 'Product SKU',
    description:
      'wt.pn_sku identifies the stock keeping unit (SKU), which is a unique numeric identifier of the product.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/products.htm#wt.pn_sku',
    reportingNameNote:
      'Collection name wt.pn_sku; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.pn_su',
    displayName: 'Product supplier',
    description: 'wt.pn_su identifies the supplier of the product.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/products.htm#wt.pn_sku',
    reportingNameNote:
      'Collection name wt.pn_su; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.ria_a',
    displayName: 'RIA name',
    description:
      'wt.ria_a identifies the name of the rich internet application (RIA) that was accessed.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/content.htm#wt.ria_a',
    reportingNameNote:
      'Collection name wt.ria_a; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.ria_c',
    displayName: 'RIA content',
    description: 'wt.ria_c identifies the rich internet application (RIA) content.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/content.htm#wt.ria_c',
    reportingNameNote:
      'Collection name wt.ria_c; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.ria_ev',
    displayName: 'RIA event',
    description:
      'wt.ria_ev identifies the rich internet application (RIA) event that occurred, such as the selection of a RIA button or feature.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/content.htm#wt.ria_ev',
    reportingNameNote:
      'Collection name wt.ria_ev; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.ria_f',
    displayName: 'RIA feature',
    description:
      'wt.ria_f identifies the rich internet application (RIA) feature that was accessed.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/content.htm#wt.ria_f',
    reportingNameNote:
      'Collection name wt.ria_f; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.rss_a',
    displayName: 'RSS article',
    description: 'wt.rss_a identifies the rich site summary (RSS) article.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/content.htm#wt.rss_a',
    reportingNameNote:
      'Collection name wt.rss_a; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.rss_ev',
    displayName: 'RSS event',
    description: 'wt.rss_ev indicates the RSS-related event, such as subscription.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/content.htm#wt.rss_ev',
    reportingNameNote:
      'Collection name wt.rss_ev; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.rss_f',
    displayName: 'RSS feed',
    description: 'wt.rss_f identifies the rich site summary (RSS) subscription feed.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/content.htm#wt.rss_f',
    reportingNameNote:
      'Collection name wt.rss_f; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.rv',
    displayName: 'Registered visitor',
    description: 'wt.rv indicates whether the visitor is registered ( 1 ) or not (null).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/registered-visitor.htm',
    reportingNameNote:
      'Collection name wt.rv; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.sdk_v',
    displayName: 'Mobile SDK Build',
    description: 'wt.sdk_v indicates the version of the Oracle Infinity mobile SDK.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.sdk_v',
    reportingNameNote:
      'Collection name wt.sdk_v; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.seg',
    displayName: 'Segment',
    description: 'wt.seg identifies values associated with a segment of interest.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/segment.htm',
    reportingNameNote:
      'Collection name wt.seg; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.si_cs',
    displayName: 'Conversion step',
    description:
      'wt.si_cs indicates whether the scenario analysis step is the one in which conversion occurs ( 1 ) or not ( 0 ).',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/wt.si_cs.htm',
    reportingNameNote:
      'Collection name wt.si_cs; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.si_n',
    displayName: 'Scenario Name',
    description: 'wt.si_n specifies the name of the scenario analysis.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/wt.si_n.htm',
    reportingNameNote:
      'Collection name wt.si_n; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.si_p',
    displayName: 'Scenario Step Name',
    description: 'wt.si_p specifies the name of the scenario analysis step.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/wt.si_p.htm',
    reportingNameNote:
      'Collection name wt.si_p; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.si_x',
    displayName: 'Scenario Step Number',
    description: 'wt.si_x specifies the numeric position of the scenario analysis step.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/wt.si_x.htm',
    reportingNameNote:
      'Collection name wt.si_x; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.site',
    displayName: 'Site ID',
    description: 'wt.site indicates the site ID for one or more events on the same hit.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/site_id.htm',
    reportingNameNote:
      'Collection name wt.site; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.sr',
    displayName: 'Screen resolution',
    description: 'wt.sr indicates the web client’s screen resolution.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/web-client.htm#wt.sr',
    reportingNameNote:
      'Collection name wt.sr; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.srch',
    displayName: 'Search engine type',
    description:
      'wt.srch differentiates a paid search engine result from a reference to an organic search engine result.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/search_engine_type.htm',
    reportingNameNote:
      'Collection name wt.srch; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.ssl',
    displayName: 'HTTPS enabled',
    description:
      "wt.ssl indicates whether the hit's content is secured via HTTPS ( 1 ) or not ( 0 ).",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/https.htm',
    reportingNameNote:
      'Collection name wt.ssl; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.sv',
    displayName: 'Server',
    description: 'wt.sv identifies the name of the web server that served up the web content.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/server.htm',
    reportingNameNote:
      'Collection name wt.sv; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.sys',
    displayName: 'Mobile App Version',
    description: 'wt.sys indicates the name of the mobile app event.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/mobile.htm#wt.sys',
    reportingNameNote:
      'Collection name wt.sys; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.ti',
    displayName: 'Page Title',
    description:
      'wt.ti identifies the HTML page title of the associated web content or the name of the mobile app in the case of the SDK.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/title.htm',
    reportingNameNote:
      'Collection name wt.ti; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tm_domcontentloaded',
    displayName: 'Load time',
    description:
      'wt.tm_domContentLoaded indicates the milliseconds taken to fully load the content in the browser, including the time needed to render content and execute downloaded scripts.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/page_load.htm#wt.tm_domContentLoaded',
    reportingNameNote:
      'Collection name wt.tm_domcontentloaded; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tm_pagedns',
    displayName: 'Page domain lookup time',
    description:
      'wt.tm_pageDns indicates the milliseconds taken to lookup the domain name for the current document.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/page_load.htm#wt.tm_pagedns',
    reportingNameNote:
      'Collection name wt.tm_pagedns; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tm_pagedownload',
    displayName: 'Page download time',
    description: 'wt.tm_pageDownload indicates the milliseconds taken to download the markup.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/page_load.htm#wt.tm_pagedownload',
    reportingNameNote:
      'Collection name wt.tm_pagedownload; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tm_pageready',
    displayName: 'Page load time',
    description: 'wt.tm_pageReady indicates the milliseconds taken before the page onReady event.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/page_load.htm#wt.tm_pageready',
    reportingNameNote:
      'Collection name wt.tm_pageready; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tm_pageredir',
    displayName: 'Page redirect time',
    description:
      'wt.tm_pageRedir indicates the milliseconds taken for the redirect if a page redirect occurs.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/page_load.htm#wt.tm_pageredir',
    reportingNameNote:
      'Collection name wt.tm_pageredir; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tm_serverconn',
    displayName: 'Page connection time',
    description:
      'wt.tm_serverConn indicates the milliseconds taken to connect to the server and for the server to respond to the connection request.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/page_load.htm#wt.tm_serverconn',
    reportingNameNote:
      'Collection name wt.tm_serverconn; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tm_serverresponse',
    displayName: 'Server response time',
    description:
      'wt.tm_serverResponse indicates the milliseconds taken to receive the page from the server.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/page_load.htm#wt.tm_serverresponse',
    reportingNameNote:
      'Collection name wt.tm_serverresponse; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tm_tv',
    displayName: 'Plugin version',
    description: 'wt.tm_tv indicates the version of the page load tracking tag plugin.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/page_load.htm#wt.tm_tv',
    reportingNameNote:
      'Collection name wt.tm_tv; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tsrc',
    displayName: 'Traffic source',
    description:
      'wt.tsrc classifies the origin of site traffic into one of a list of possible values based on the referrer of the collected data.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/data_augmentation/traffic_source_and_search.htm#wt.tsrc',
    reportingNameNote:
      'Collection name wt.tsrc; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tu',
    displayName: 'URL truncation',
    description:
      'wt.tu indicates the maximum URL length limitation was imposed by Microsoft Internet Explorer.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/url_truncation.htm',
    reportingNameNote:
      'Collection name wt.tu; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tv',
    displayName: 'JavaScript tag version',
    description: 'wt.tv specifies the version of the JavaScript tag that is currently deployed.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/js_tag_version.htm',
    reportingNameNote:
      'Collection name wt.tv; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tx_cartid',
    displayName: 'Cart ID',
    description: "wt.tx_cartid indicates a unique ID for the visitor's cart.",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/transaction.htm#wt.tx_cartid',
    reportingNameNote:
      'Collection name wt.tx_cartid; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tx_e',
    displayName: 'Transaction Event',
    description:
      'wt.tx_e identifies the type of transaction and is used as qualifier in measure definitions along with wt.tx_u to determine which product to count.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/transaction.htm#wt.tx_e',
    reportingNameNote:
      'Collection name wt.tx_e; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tx_i',
    displayName: 'Invoice number',
    description: 'wt.tx_i identifies the invoice number for the purchase.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/invoice.htm#wt.tx_i',
    reportingNameNote:
      'Collection name wt.tx_i; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tx_id',
    displayName: 'Invoice date',
    description:
      'wt.tx_id identifies the UTC-based invoice date of a purchase to prevent the erroneous recording of purchases.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/invoice.htm#wt.tx_id',
    reportingNameNote:
      'Collection name wt.tx_id; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tx_it',
    displayName: 'Invoice time',
    description:
      'wt.tx_it identifies the UTC-based invoice time of the purchase and is used to prevent the erroneous recording of purchases.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/invoice.htm#wt.tx_it',
    reportingNameNote:
      'Collection name wt.tx_it; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tx_s',
    displayName: 'Transaction Subtotal',
    description: 'wt.tx_s identifies the total cost for each product in the order.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/transaction.htm#wt.tx_s',
    reportingNameNote:
      'Collection name wt.tx_s; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tx_u',
    displayName: 'Units',
    description: 'wt.tx_u identifies the quantity in the transaction.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/transaction.htm#wt.tx_u',
    reportingNameNote:
      'Collection name wt.tx_u; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.tz',
    displayName: 'Time zone',
    description: "wt.tz indicates the web client's time zone offset from UTC.",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/web-client.htm#wt.tz',
    reportingNameNote:
      'Collection name wt.tz; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.ul',
    displayName: 'User language',
    description: "wt.ul indicates the app or web client's user language.",
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/web-client.htm#wt.ul',
    reportingNameNote:
      'Collection name wt.ul; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.vt_a_s',
    displayName: 'New visitor for account',
    description:
      '(Deprecated) wt.vt_a_s indicates the first hit from a new visitor for a specified account.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_tracking.htm#wt.vt_a_s',
    reportingNameNote:
      'Collection name wt.vt_a_s; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.vt_d',
    displayName: 'First hit of day',
    description: '(Deprecated) wt.vt_d indicates the first hit of the day from the visitor.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_tracking.htm#wt.vt_d',
    reportingNameNote:
      'Collection name wt.vt_d; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.vt_f',
    displayName: 'First Visit',
    description:
      'wt.vt_f indicates a new or returning visitor that accepts first-party cookies ( 1 ) or who has disabled first-party cookies ( 2 ). This parameter is no longer in use by Oracle Infinity Analytics.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_tracking.htm#wt.vt_f',
    reportingNameNote:
      'Collection name wt.vt_f; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.vt_f_a',
    displayName: 'New visitor for an account',
    description: '(Deprecated) wt.vt_f_a indicates a new visitor for an account.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_tracking.htm#wt.vt_f_a',
    reportingNameNote:
      'Collection name wt.vt_f_a; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.vt_f_s',
    displayName: 'First hit for new visitor session',
    description: '(Deprecated) wt.vt_f_s indicates the first hit from a new visitor session.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_tracking.htm#wt.vt_f_s',
    reportingNameNote:
      'Collection name wt.vt_f_s; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.vt_s',
    displayName: 'First hit of new session',
    description: '(Deprecated) wt.vt_s indicates the first hit for a new session.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_tracking.htm#wt.vt_s',
    reportingNameNote:
      'Collection name wt.vt_s; reporting contexts may expose it with a data. prefix.',
  },
  {
    name: 'wt.vtid',
    displayName: 'Visitor ID',
    description:
      '(Deprecated) wt.vtid provides a hashed visitor ID to sessionize visitors for use in reporting.',
    sensitivity: 'none',
    sourceUrl:
      'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/visitor_tracking.htm#wt.vtid',
    reportingNameNote:
      'Collection name wt.vtid; reporting contexts may expose it with a data. prefix.',
  },
] satisfies OracleParameterCatalogEntry[];
