import type { OracleParameterCatalogEntry, ParameterSensitivity } from '../models';
import { FULL_REFERENCE_PARAMETER_ENTRIES } from './oracleParameterCatalog.generated';
import { COMMERCE_GUIDE_URL } from './infinityDocumentation';

export { COMMERCE_GUIDE_URL } from './infinityDocumentation';

const fullReference =
  'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/reference.htm';
const defaultParameters =
  'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/data_collection/default_data.htm';
const blocklistReference =
  'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/data_collection/blocklist_tag_plugin.htm';
const pixelReference =
  'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/pixel_tracking/pixeltracking_impguide.htm';
const eventTrackerReference =
  'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/data_collection/event_tracker_plugin.htm';
const mobileClientReference =
  'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/data_collection/mobile_client_plugin.htm';
const linkTrackingReference =
  'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/data_collection/link_tracking_plugin_ref.htm';
const supplementalSystemNames = [
  'wt.vtvs',
  'wt.vt_tlv',
  'wt.vt_a_d',
  'wt.vt_sid',
  'wt.si_s',
  'wt.seg_1',
  'wt.seg_2',
  'wt.seg_3',
  'wt.seg_4',
] as const;

const supplementalEntries: OracleParameterCatalogEntry[] = [
  {
    name: 'dcssip',
    displayName: 'Domain',
    description: 'Domain visited for the collected event.',
    sensitivity: 'none',
    sourceUrl: defaultParameters,
  },
  {
    name: 'dcsuri',
    displayName: 'URI stem',
    description: 'Portion of the collected URL after the domain.',
    sensitivity: 'none',
    sourceUrl: defaultParameters,
  },
  {
    name: 'dcsref',
    displayName: 'Referrer',
    description: 'Referrer associated with the collected event.',
    sensitivity: 'none',
    sourceUrl: mobileClientReference,
  },
  {
    name: 'dcsqry',
    displayName: 'URL query string',
    description: 'Query-string portion associated with the tracked URL.',
    sensitivity: 'none',
    sourceUrl: linkTrackingReference,
  },
  {
    name: 'dcsdat',
    displayName: 'Tag-generated timestamp',
    description:
      'Timestamp-like value generated by the Oracle Infinity Tag and shown in official payload examples; Oracle’s public Full Parameter Reference does not define its exact semantics.',
    sensitivity: 'none',
    sourceUrl: pixelReference,
  },
  {
    name: 'ora.inf.account',
    displayName: 'Oracle Infinity account',
    description: 'Account GUID that routes a pixel or redirect event to the intended account.',
    sensitivity: 'identifier',
    sourceUrl: pixelReference,
  },
  {
    name: 'ora.redir',
    displayName: 'Redirect target',
    description: 'URL-encoded target used after Oracle Infinity records a redirect-tracking event.',
    sensitivity: 'none',
    sourceUrl: pixelReference,
  },
  {
    name: 'ora.tag_config',
    displayName: 'Oracle tag configuration',
    description: 'Tag configuration value included in documented Oracle Infinity payloads.',
    sensitivity: 'none',
    sourceUrl: pixelReference,
  },
  {
    name: 'ora.tag_id',
    displayName: 'Oracle tag ID',
    description: 'Identifier for the Oracle Infinity Tag configuration used to collect the event.',
    sensitivity: 'identifier',
    sourceUrl: blocklistReference,
  },
  {
    name: 'wt.deferredpayload',
    displayName: 'Deferred payload',
    description: 'Set to 1 by the Event Tracker plugin to identify a deferred hit.',
    sensitivity: 'none',
    sourceUrl: eventTrackerReference,
    reportingNameNote:
      'Collection name wt.deferredpayload; reporting contexts may expose it with a data. prefix.',
  },
  ...supplementalSystemNames.map((name): OracleParameterCatalogEntry => ({
    name,
    displayName: name,
    description: `${name} is an Oracle-documented system parameter listed in the Infinity Tag default whitelist; Oracle’s public Full Parameter Reference does not provide a definition.`,
    sensitivity: name === 'wt.vt_sid' ? 'identifier' : 'none',
    sourceUrl: blocklistReference,
    reportingNameNote: `Collection name ${name}; reporting contexts may expose it with a data. prefix.`,
  })),
];

const commerceEntries: OracleParameterCatalogEntry[] = [
  ['domain', 'Domain', 'Domain associated with the commerce event.'],
  ['wt.product_name', 'Product name', 'Name of each product, delimited by line item.'],
  ['wt.product_price', 'Product unit price', 'Unit price of each product, delimited by line item.'],
  ['wt.currency', 'Currency', 'Currency code used for the commerce values.'],
  ['wt.product_discount', 'Product discount', 'Discount for each product, delimited by line item.'],
  ['wt.product_variant', 'Product variant', 'Variant of each product, delimited by line item.'],
  ['wt.cart_subtotal', 'Cart subtotal', 'Subtotal for the shopping cart.'],
  ['wt.cart_total', 'Cart total', 'Total value of the shopping cart.'],
  ['wt.cart_tax', 'Cart tax', 'Tax applied to the shopping cart.'],
  ['wt.cart_shipping', 'Cart shipping', 'Shipping amount applied to the shopping cart.'],
  ['wt.cart_discount', 'Cart discount', 'Discount applied to the entire shopping cart.'],
  ['wt.cart_coupon', 'Cart coupon', 'Coupon code applied to the shopping cart.'],
  [
    'wt.email_sha256',
    'SHA-256 hashed email address',
    'SHA-256 hashed email used for person-level connections.',
  ],
].map(([name, displayName, description]) => ({
  name,
  displayName,
  description,
  sensitivity: name === 'wt.email_sha256' ? 'identifier' : 'none',
  sourceUrl: COMMERCE_GUIDE_URL,
  reportingNameNote: name.startsWith('wt.')
    ? `Collection name ${name}; reporting contexts may expose it with a data. prefix.`
    : undefined,
})) as OracleParameterCatalogEntry[];

const sensitivityOverrides: Record<string, ParameterSensitivity> = {
  'ext.device.id': 'identifier',
  'session.session_id': 'identifier',
  'session.visitor_id': 'identifier',
  'wt.co_f': 'identifier',
  'wt.dcsvid': 'identifier',
  'wt.p_did': 'identifier',
  'wt.p_pid': 'identifier',
  'wt.p_sid': 'identifier',
  'wt.p_vid': 'identifier',
  'wt.pn_id': 'identifier',
  'wt.pn_sku': 'identifier',
  'wt.tx_cartid': 'identifier',
  'wt.tx_i': 'identifier',
  'wt.vtid': 'identifier',
};

const entries = [
  ...FULL_REFERENCE_PARAMETER_ENTRIES,
  ...supplementalEntries,
  ...commerceEntries,
].map((entry) => ({
  ...entry,
  sensitivity: sensitivityOverrides[entry.name] ?? entry.sensitivity,
}));

export const ORACLE_PARAMETER_CATALOG = {
  version: '2026.07-commerce.1',
  coverage: 'full-reference-plus-official-supplements' as const,
  lastVerifiedDate: '2026-07-13',
  sourceDocumentationUrls: [
    fullReference,
    defaultParameters,
    blocklistReference,
    pixelReference,
    eventTrackerReference,
    mobileClientReference,
    linkTrackingReference,
    COMMERCE_GUIDE_URL,
  ],
  entries,
};

export function catalogMap(imported: OracleParameterCatalogEntry[] = []) {
  return new Map(
    [...ORACLE_PARAMETER_CATALOG.entries, ...imported].map((entry) => [
      entry.name.toLowerCase(),
      entry,
    ]),
  );
}
