import { createServer } from 'node:http';
import { mkdir, readFile, stat } from 'node:fs/promises';
import { extname, join, resolve } from 'node:path';
import { chromium } from '@playwright/test';

const root = resolve(import.meta.dirname, '..');
const dist = join(root, 'dist');
const output = join(root, 'docs', 'images');
const packageJson = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
const capturedAt = '2026-07-13T22:30:00.000Z';
const pageUrl = 'https://shop.example.test/products/insulated-bottle';

function parameter(eventId, index, name, value, classification, options = {}) {
  return {
    id: `${eventId}:query-string:${encodeURIComponent(name)}:${index}`,
    name,
    value,
    sourceType: 'cx-tag-network',
    eventTimestamp: capturedAt,
    eventId,
    origin: 'query-string',
    classification,
    sensitivity: options.sensitivity ?? 'none',
    catalogDisplayName: options.displayName,
    catalogDescription: options.description,
    namingPattern:
      classification === 'standard' ? 'Oracle catalog match' : 'implementation-defined parameter',
  };
}

const viewParameters = [
  parameter('event-view', 0, 'dcsdat', '1783982327833', 'standard', {
    displayName: 'Tag-generated timestamp',
    description: 'Timestamp-like value generated by the Oracle Infinity Tag.',
  }),
  parameter('event-view', 1, 'wt.dl', '0', 'standard', {
    displayName: 'Event type',
    description: 'Identifies the collected event type.',
  }),
  parameter('event-view', 2, 'wt.ti', 'Insulated Bottle', 'standard', {
    displayName: 'Page Title',
    description: 'Title of the viewed page.',
  }),
  parameter('event-view', 3, 'wt.co_f', 'demo-visitor-7a92', 'standard', {
    sensitivity: 'identifier',
    displayName: 'Visitor ID',
    description: 'Documented Infinity visitor identifier.',
  }),
  parameter('event-view', 4, 'site.section', 'products', 'custom'),
  parameter('event-view', 5, 'content.language', 'en-US', 'custom'),
  parameter('event-view', 6, 'site.campaign', '', 'custom'),
  parameter('event-view', 7, 'wt.z_experiment', 'hero-a', 'unknown'),
];
const clickParameters = [
  parameter('event-click', 0, 'dcsdat', '1783982331154', 'standard', {
    displayName: 'Tag-generated timestamp',
  }),
  parameter('event-click', 1, 'wt.dl', '25', 'standard', { displayName: 'Event type' }),
  parameter('event-click', 2, 'wt.ev', 'Add to Cart', 'standard', {
    displayName: 'Event name',
  }),
  parameter('event-click', 3, 'product.sku', 'BOTTLE-24-BLUE', 'custom'),
  parameter('event-click', 4, 'product.quantity', '1', 'custom'),
];

const session = {
  schemaVersion: 1,
  pageUrl,
  loaders: [
    {
      id: 'loader-demo',
      platformId: 'oracle-infinity',
      sourceUrl:
        'https://d.oracleinfinity.io/infy/acs/account/demo-account-guid/js/demo-tag/odc.js?_ora.config=analytics:test',
      config: {
        accountGuid: 'demo-account-guid',
        tagId: 'demo-tag',
        config: 'analytics:test',
        environmentGuess: 'test',
      },
      location: {
        path: 'html > head > script:nth-of-type(3)',
        parentElement: 'head',
        scriptIndex: 2,
        inHead: true,
      },
      async: true,
      defer: false,
      dynamicallyInserted: false,
      inlineLoaderEvidence: false,
      parserInsertedInference: false,
      loadMode: 'asynchronous',
      confidence: 'observed',
      evidence: [{ kind: 'async-attribute', description: 'Script uses async.', direct: true }],
      detectedAt: capturedAt,
    },
  ],
  tagManagers: [
    {
      id: 'tag-manager-demo',
      type: 'google-tag-manager',
      label: 'Google Tag Manager',
      containerId: 'GTM-DEMO123',
      sourceUrl: 'https://www.googletagmanager.com/gtm.js?id=GTM-DEMO123',
      location: { path: 'html > head > script:nth-of-type(1)', parentElement: 'head' },
      confidence: 'observed',
      evidence: 'Google Tag Manager script URL and container identifier observed.',
      detectedAt: capturedAt,
    },
  ],
  observations: [
    {
      id: 'event-view',
      platformId: 'oracle-infinity',
      timestamp: capturedAt,
      requestUrl:
        'https://demo.dc.oracleinfinity.io/dcs.gif?dcsdat=1783982327833&wt.dl=0&wt.ti=Insulated%20Bottle&site.section=products',
      requestMethod: 'GET',
      statusCode: 200,
      sourceType: 'cx-tag-network',
      eventKind: 'page-view',
      wtDl: '0',
      accountGuid: 'demo-account-guid',
      parameterCount: viewParameters.length,
      requestBodyParseStatus: 'success',
      responseStatus: '200 OK',
      warnings: [],
      parameters: viewParameters,
    },
    {
      id: 'event-click',
      platformId: 'oracle-infinity',
      timestamp: '2026-07-13T22:30:03.154Z',
      requestUrl:
        'https://demo.dc.oracleinfinity.io/dcs.gif?dcsdat=1783982331154&wt.dl=25&wt.ev=Add%20to%20Cart&product.sku=BOTTLE-24-BLUE',
      requestMethod: 'GET',
      statusCode: 200,
      sourceType: 'cx-tag-network',
      eventKind: 'click-event',
      wtDl: '25',
      accountGuid: 'demo-account-guid',
      parameterCount: clickParameters.length,
      requestBodyParseStatus: 'success',
      responseStatus: '200 OK',
      warnings: [],
      parameters: clickParameters,
    },
    {
      id: 'library-ubi',
      platformId: 'oracle-infinity',
      timestamp: '2026-07-13T22:29:59.000Z',
      requestUrl: 'https://d.oracleinfinity.io/infy/ubi/analytics/ubi.js?v=demo',
      requestMethod: 'GET',
      statusCode: 304,
      sourceType: 'infinity-library',
      eventKind: 'library',
      parameterCount: 0,
      requestBodyParseStatus: 'not-applicable',
      responseStatus: '304 Not Modified',
      warnings: [],
      parameters: [],
      libraryName: 'ubi.js',
      libraryType: 'javascript',
    },
  ],
  scannedAt: capturedAt,
  timeline: [],
  droppedObservationCount: 0,
};

const popupSummary = {
  pageUrl,
  platformId: 'oracle-infinity',
  scannedAt: capturedAt,
  summary: {
    tagStatus: 'detected',
    loaderCount: 1,
    libraryCount: 1,
    libraryIssueCount: 0,
    tagManagerCount: 1,
    collectionEventCount: 2,
    cxTagEventCount: 2,
    dcApiEventCount: 0,
    supportTrafficCount: 0,
    standardParameterCount: 7,
    customParameterCount: 5,
    unknownParameterCount: 1,
    warningCount: 4,
    confidence: 'observed',
    reloadRecommended: false,
  },
  warnings: [
    { severity: 'medium', title: 'Empty parameter value observed' },
    { severity: 'low', title: 'Observed parameter needs review' },
    { severity: 'low', title: 'Network capture may be incomplete' },
  ],
};

const contentTypes = {
  '.css': 'text/css',
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript',
  '.json': 'application/json',
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
};
const server = createServer(async (request, response) => {
  try {
    const pathname = decodeURIComponent(new URL(request.url ?? '/', 'http://localhost').pathname);
    const file = resolve(dist, `.${pathname}`);
    if (!file.startsWith(dist) || !(await stat(file)).isFile()) {
      response.writeHead(404).end('Not found');
      return;
    }
    response.writeHead(200, {
      'content-type': contentTypes[extname(file)] ?? 'application/octet-stream',
    });
    response.end(await readFile(file));
  } catch {
    response.writeHead(404).end('Not found');
  }
});
await new Promise((resolveListen, reject) => {
  server.once('error', reject);
  server.listen(0, '127.0.0.1', resolveListen);
});
const address = server.address();
if (!address || typeof address === 'string') throw new Error('Unable to start screenshot server.');
const baseUrl = `http://127.0.0.1:${address.port}`;

const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  await mkdir(output, { recursive: true });
  const context = await browser.newContext({
    viewport: { width: 1600, height: 1000 },
    deviceScaleFactor: 1,
    colorScheme: 'light',
  });
  await context.addInitScript(
    ({ sessionData, summaryData, extensionVersion }) => {
      const runtimeListeners = new Set();
      const event = { addListener() {}, removeListener() {} };
      Object.assign(globalThis.chrome ?? (globalThis.chrome = {}), {
        runtime: {
          getManifest: () => ({ version: extensionVersion }),
          onMessage: {
            addListener: (listener) => runtimeListeners.add(listener),
            removeListener: (listener) => runtimeListeners.delete(listener),
          },
          sendMessage: async (message) => {
            if (message.type === 'GET_TAB_SESSION') return sessionData;
            if (message.type === 'GET_TAB_SUMMARY') return summaryData;
            if (message.type === 'GET_ACTIVE_TAB_ID') return { tabId: 42 };
            if (message.type === 'GET_VERSION') return { version: extensionVersion };
            if (message.type === 'SCAN_TAB_DOM_ONCE') return { ok: true };
            return { ok: true };
          },
        },
        storage: {
          local: { get: async () => ({}), set: async () => undefined },
        },
        tabs: {
          query: async () => [{ id: 42, url: sessionData.pageUrl }],
        },
        devtools: {
          inspectedWindow: {
            tabId: 42,
            eval: (expression, callback) =>
              callback(expression === 'location.href' ? sessionData.pageUrl : true, undefined),
            reload() {},
          },
          network: {
            getHAR: (callback) => callback({ entries: [] }),
            onRequestFinished: event,
            onNavigated: event,
          },
        },
      });
      Object.defineProperty(navigator, 'clipboard', {
        configurable: true,
        value: { writeText: async () => undefined },
      });
    },
    { sessionData: session, summaryData: popupSummary, extensionVersion: packageJson.version },
  );

  const popup = await context.newPage();
  await popup.setViewportSize({ width: 480, height: 900 });
  await popup.goto(`${baseUrl}/popup.html`);
  await popup.getByRole('heading', { name: 'Page QA companion' }).waitFor();
  await popup.locator('main').screenshot({ path: join(output, 'popup-companion.png') });

  const panel = await context.newPage();
  await panel.setViewportSize({ width: 1600, height: 700 });
  await panel.goto(`${baseUrl}/panel.html`);
  await panel.getByRole('heading', { name: 'Implementation Inspector' }).waitFor();
  await panel.screenshot({ path: join(output, 'overview.png') });
  await panel.getByRole('button', { name: 'Network Events' }).click();
  await panel.setViewportSize({ width: 1600, height: 1000 });
  await panel.getByRole('heading', { name: 'Captured events' }).waitFor();
  await panel.screenshot({ path: join(output, 'network-event-details.png'), fullPage: true });
  await context.close();
  console.log('Captured sanitized popup, overview, and network-event documentation screenshots.');
} finally {
  await browser.close();
  await new Promise((resolveClose) => server.close(resolveClose));
}
