/* global fetch */
import { log } from 'node:console';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath, URL } from 'node:url';

const referenceUrl =
  'https://docs.oracle.com/en/cloud/saas/marketing/infinity-develop/docs/parameters/reference.htm';
const outputUrl = new URL(
  '../src/features/infinity/oracleParameterCatalog.generated.ts',
  import.meta.url,
);

function decodeHtml(value) {
  return value
    .replace(/&#(\d+);/g, (_match, code) => String.fromCodePoint(Number(code)))
    .replace(/&#x([a-f0-9]+);/gi, (_match, code) => String.fromCodePoint(Number.parseInt(code, 16)))
    .replace(/&nbsp;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&quot;/gi, '"')
    .replace(/&#39;|&apos;/gi, "'")
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>');
}

function textContent(value) {
  return decodeHtml(value.replace(/<[^>]+>/g, ' '))
    .replace(/\s+/g, ' ')
    .replace(/\s+([.,;:!?])/g, '$1')
    .replace(/\s+'s\b/g, "'s")
    .trim();
}

const response = await fetch(referenceUrl);
if (!response.ok) throw new Error(`Oracle reference request failed with HTTP ${response.status}.`);
const html = await response.text();
const entries = [];

for (const row of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)) {
  const cells = [...row[1].matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)];
  if (cells.length < 3) continue;
  const name = textContent(cells[0][1]);
  if (!/^[a-z][a-z0-9_.-]*$/i.test(name)) continue;
  const displayName = textContent(cells[1][1]) || name;
  const description = textContent(cells[2][1]) || displayName;
  const href = cells[0][1].match(/<a\b[^>]*href="([^"]+)"/i)?.[1];
  entries.push({
    name: name.toLowerCase(),
    displayName,
    description,
    sensitivity: 'none',
    sourceUrl: href ? new URL(decodeHtml(href), referenceUrl).href : referenceUrl,
    ...(name.toLowerCase().startsWith('wt.')
      ? {
          reportingNameNote: `Collection name ${name.toLowerCase()}; reporting contexts may expose it with a data. prefix.`,
        }
      : {}),
  });
}

const uniqueEntries = [...new Map(entries.map((entry) => [entry.name, entry])).values()].sort(
  (left, right) => left.name.localeCompare(right.name),
);
if (uniqueEntries.length < 150) {
  throw new Error(
    `Only ${uniqueEntries.length} parameters were parsed; refusing to replace the catalog.`,
  );
}

const source = `// Generated from Oracle's Full Parameter Reference by scripts/syncOracleParameterCatalog.mjs.
// Do not edit this file by hand; update the generator or supplemental catalog instead.
import type { OracleParameterCatalogEntry } from '../models';

export const FULL_REFERENCE_PARAMETER_ENTRIES = ${JSON.stringify(uniqueEntries, null, 2)} satisfies OracleParameterCatalogEntry[];
`;

await writeFile(fileURLToPath(outputUrl), source, 'utf8');
log(`Wrote ${uniqueEntries.length} Oracle parameters to ${fileURLToPath(outputUrl)}.`);
